[versions]
agp = "8.3.1"
firebaseCore = "21.1.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
glide = "5.0.0-rc01"
googleServices = "4.4.1"
firebaseFirestore = "24.11.1"
firebaseDatabase = "20.3.1"
firebaseAuth = "22.3.1"
googleGmsGoogleServices = "4.4.1"
firebaseStorage = "21.0.0"
firebaseFirestoreVersion = "25.0.0"

[libraries]
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
junit = { group = "junit", name = " ", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version = "23.0.0" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
google-firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestoreVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
googleGmsGoogleServices = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }



